{
    "name": "Barcode Scanner",
    "version": "18.0.1.0.0",
    "category": "Hidden",
    "summary": "Base scanning framework: client action, registries, scanner input and hooks",
    "author": "Binhex, Odoo Community Association (OCA)",
    "website": "https://github.com/RocketCloudSaaS/barcode",
    "maintainers": ["szalatyzuzanna"],
    "license": "AGPL-3",
    "depends": [
        "web",
    ],
    "data": [
        "views/action.xml",
        "views/templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "barcode_scanner/static/src/scss/barcode_scanner.scss",
            "barcode_scanner/static/src/xml/barcode_scanner_templates.xml",
            "barcode_scanner/static/src/js/registries.js",
            "barcode_scanner/static/src/js/barcode_parser.js",
            "barcode_scanner/static/src/js/barcode.js",
            "barcode_scanner/static/src/js/api.js",
            "barcode_scanner/static/src/js/router.js",
            "barcode_scanner/static/src/js/store.js",
            "barcode_scanner/static/src/js/app.js",
            "barcode_scanner/static/src/js/services/feedback_service.js",
            "barcode_scanner/static/src/js/hooks/use_barcode.js",
            "barcode_scanner/static/src/js/hooks/use_barcode_handler.js",
            "barcode_scanner/static/src/js/hooks/use_barcode_dispatcher.js",
            "barcode_scanner/static/src/js/hooks/use_inventory.js",
            "barcode_scanner/static/src/js/screens/main_screen.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
